spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gonnys?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true 
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gonnys
    password: 12345678
    
  thymeleaf:
    cache: false
    



server:
  port: 8080

  


logging:
  level:
    org.hibernate: debug
    org.springframework: info
    org.salem: debug